### ISSUE TITLE
Issue with generateECKeyPairWithParams and generateRSAKeyPairWithParams

### ISSUE THREAD

**Issue by Prabhanshu1986** [aws-samples/aws-cloudhsm-jce-examples#23]
java.lang.NoClassDefFoundError: Could not initialize class com.cavium.key.CaviumRSAPrivateKey
        at com.cavium.cfm2.Generator.generateRSAKeyPair(Generator.java:97) ~[cloudhsm-2.0.3.jar!/:na]
        at com.cavium.key.generator.CaviumRSAKeyPairGenerator.generateKeyPair(CaviumRSAKeyPairGenerator.java:71) ~[cloudhsm-2.0.3.jar!/:na]
        at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:697) ~[na:1.8.0_212]
        at com.sabre.awshsmconnector.AsymmetricKeys.generateRSAKeyPairWithParams(AsymmetricKeys.java:93) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.AsymmetricKeys.generateRSAKeyPair(AsymmetricKeys.java:82) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.RSAOperationsRunner.encryptRSA(RSAOperationsRunner.java:147) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.LoginHSM.loginHSMEncryptData(LoginHSM.java:92) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.AwsController.encryptedResponse(AwsController.java:17) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.1.6.RELEASE.jar!/:5.1.6.RELE
****************************************************************************************************************************************************************************************************************************		
		
java.lang.NoClassDefFoundError: Could not initialize class com.cavium.key.generator.CaviumECKeyPairGenerator
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
        at java.security.Provider$Service.newInstance(Provider.java:1595) ~[na:1.8.0_212]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:236) ~[na:1.8.0_212]
        at sun.security.jca.GetInstance.getInstance(GetInstance.java:206) ~[na:1.8.0_212]
        at java.security.KeyPairGenerator.getInstance(KeyPairGenerator.java:279) ~[na:1.8.0_212]
        at com.sabre.awshsmconnector.AsymmetricKeys.generateECKeyPairWithParams(AsymmetricKeys.java:55) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.AsymmetricKeys.generateECKeyPair(AsymmetricKeys.java:49) ~[classes!/:0.0.1-SNAPSHOT]

**Comment by rday** [comment]
I was able to run the key utility import test with the 2.0.3 release. Do you have a build example that is failing? Is the jar file available at runtime?

**Comment by Prabhanshu1986** [comment]
I am getting this with key utilities runner
java.lang.NoClassDefFoundError: Could not initialize class com.cavium.key.CaviumECPrivateKey
        at com.sabre.awshsmconnector.KeyUtilitiesRunner.getKeyByHandle(KeyUtilitiesRunner.java:241) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.KeyUtilitiesRunner.keyUtility(KeyUtilitiesRunner.java:185) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.LoginHSM.loginHSMEncryptData(LoginHSM.java:98) ~[classes!/:0.0.1-SNAPSHOT]
        at com.sabre.awshsmconnector.AwsController.encryptedResponse(AwsController.java:17) ~[classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102) ~[spring-webmvc-5.

**Comment by rday** [comment]
Can you build and run the sample using Maven? If we can eliminate the sabre classes, then I can try to reproduce locally.

**Comment by Prabhanshu1986** [comment]
Login HSM is successful 
Only ECBEncryptDecryptRunner is working for me i.e generating an AES key and encrypting.

I think when it comes to new Cavium.. classes it is failing

**Comment by Prabhanshu1986** [comment]
I mean when it tries to create instances of Cavium variants

**Comment by Prabhanshu1986** [comment]
snapshot of POM. I copied cloudhasm2.0.3 jar to the highlighted C:/ location and also to my maven repository     
   <dependency>
            <groupId>com.cavium</groupId>
            <artifactId>cloudhsm</artifactId>
            **<version>2.0.3</version>**
        </dependency> 

   <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>2.5.1</version>
                <executions>
                    <execution>
                        <id>install-log4j-core</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <groupId>org.apache.logging.log4j-core</groupId>
                            <artifactId>log4j-core</artifactId>
                            <version>2.8</version>
                            <packaging>jar</packaging>
                            <file>C:/aws_hsm_jars/log4j-core-2.8.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-log4j-api</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <groupId>org.apache.logging.log4j-api</groupId>
                            <artifactId>log4j-api</artifactId>
                            <version>2.8</version>
                            <packaging>jar</packaging>
                            <file>C:/aws_hsm_jars/log4j-api-2.8.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install-cloudhsm-jce</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>validate</phase>
                        <configuration>
                            <groupId>com.cavium</groupId>
                            <artifactId>cloudhsm</artifactId>
                            <version>2.0.3</version>
                            <packaging>jar</packaging>
                            <file>**C:/aws_hsm_jars/cloudhsm-2.0.3.jar**</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by Prabhanshu1986** [comment]
All above errors were due to below exception.

java.lang.ClassCastException: org.apache.logging.slf4j.SLF4JLogger cannot be cast to org.apache.logging.log4j.core.Logger.

The issue can be closed now. Thanks for your help.
