### ISSUE TITLE
KeyUtilitiesRunner.java importRSAKey  reproting this error. Attirbutes being specified are imcomplete

### ISSUE THREAD

**Issue by LIJI-Max** [aws-samples/aws-cloudhsm-jce-examples#57]
Exception in thread "main" com.amazonaws.cloudhsm.jce.jni.exception.AttributeException: Attributes being specified are incomplete: Incomplete template
	at com.amazonaws.cloudhsm.jce.jni.RsaPrivateKeyImportBuilder.do_importKey(Native Method)
	at com.amazonaws.cloudhsm.jce.jni.RsaPrivateKeyImportBuilder.importKey(RsaPrivateKeyImportBuilder.java:35)
	at com.amazonaws.cloudhsm.jce.provider.ImportKey.importRsaPrivateKey(ImportKey.java:168)
	at com.amazonaws.cloudhsm.jce.provider.RsaKeyFactory.engineGeneratePrivate(RsaKeyFactory.java:153)
	at java.security.KeyFactory.generatePrivate(KeyFactory.java:366)
	at com.amazonaws.cloudhsm.examples.KeyUtilitiesRunner.importRsaKey(KeyUtilitiesRunner.java:268)
	at com.amazonaws.cloudhsm.examples.KeyUtilitiesRunner.main(KeyUtilitiesRunner.java:147)

**Comment by rday** [comment]
We didn't have enough information to investigate this issue. Our example code is building and executing on our side, so maybe the error is fixed. Please re-open if this is still a problem.
